name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: betester/suara:${{ github.ref_name }}

      - name: SCP to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "compose.prod.yml,compose.yml"
          target: "~"

      - name: SSH to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            ls -a
            # Set environment variables
            export IMAGE_VERSION=${{ github.ref_name }}
            export MONGO_URL=${{ secrets.MONGO_URL }}
            export DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            export DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}

            # Run Docker Compose
            docker-compose -f ~/compose.prod.yml up -d
